name: Phrase

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phrase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: winify-ag/setup-phraseapp@v2
        with:
          version: 2.0.12
      - run: |
          echo $PHRASE_INFO | base64 -d > .phraseapp.yml
        env:
          PHRASE_INFO: ${{ secrets.PHRASE_INFO }}
      - run: phrase push --wait
